library(caTools)
library(ROCR)
library(dplyr)
x <- read.csv("./Data-Science/admit.csv")
split <- sample.split(x, SplitRatio = 0.7)
train <- subset(x, split == "TRUE")
test <- subset(x, split == "FALSE")
logistic_model <- glm(admit ~ ., data = x)
pred <- predict(logistic_model, test, type = "response")
pred <- ifelse(pred > 0.5, 1, 0)
table(test$admit, pred)
missing_class <- mean(pred != test$admit)
print(paste("Accuracy =", 1 - missing_class))
roc <- prediction(pred, test$admit)
rocper <- performance(roc, measure = "tpr", x.measure = "fpr")
auc <- performance(roc, measure = "auc")
auc <- auc@y.values[[1]]
print(auc)
plot(rocper)
plot(rocper, colorize = TRUE, print.cutoffs.at = seq(0.1, by = 0.1))
abline(a = 0, b = 1)
auc <- round(auc, 4)
legend(.6, .4, auc, title = "AUC", cex = 1)