library(e1071)
library(caret)
library(caTools)
x <- read.csv("./Data-Science/salaries.csv")
split <- sample.split(x, SplitRatio = 0.8)
train <- subset(x, split == "TRUE")
test <- subset(x, split == "FALSE")
naive <- naiveBayes(company_size ~ ., data = train)
pred <- predict(naive, newdata = test)
conf <- table(test$company_size, pred)
print(confusionMatrix(conf))